title:  Python3
tagline: Enter to Learn Exit to Earn
description:  Python3 Course is designed in such way that all Learners will become practitioner

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: # the name of the repository when it is created for the learner
  repo: # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: Installation
  description: How to Install Python
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
- title: OnBoarding
  description: Welcome to Python!!
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
- title: HandsOn Lab
  description: Python Programming Handson
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
- title: OOPS
  description: Real time Scenario
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
- title: Thank you
  description: Enroll our other courses
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

